quarkus.langchain4j.ollama.base-url=http://localhost:11434/
quarkus.langchain4j.ollama.chat-model.model-id=qwen2.5:3b-instruct
quarkus.langchain4j.ollama.timeout=120s

#quarkus.langchain4j.easy-rag.path=src/main/resources/rag
#quarkus.langchain4j.easy-rag.max-overlap-size=20
#quarkus.langchain4j.easy-rag.max-segment-size=100

quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text


quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
# Drop table first before creating it, useful for development and testing, but be careful in production
quarkus.langchain4j.pgvector.drop-table-first=true

# --- Configuração de Logging do LangChain4j ---
# Loga a requisição completa enviada para o LLM (incluindo o manifesto de Tools)
quarkus.langchain4j.log-requests=true
# Loga a resposta completa recebida do LLM (incluindo a chamada de Tool)
quarkus.langchain4j.log-responses=true